# Generated by Django 4.0 on 2023-06-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_profiles_friends_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='tagged_users',
            field=models.ManyToManyField(related_name='picture_tagged_user', to='App.Profiles'),
        ),
    ]
