# Generated by Django 4.0 on 2023-06-13 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0005_alter_picture_tagged_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='tagged_users',
            field=models.ManyToManyField(related_name='picture_tagged_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
