# Generated by Django 4.0 on 2023-06-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_picture_tagged_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='picture',
            name='tagged_users',
            field=models.ManyToManyField(related_name='picture_tagged_user', to='App.Profiles'),
        ),
    ]
