# Generated by Django 4.0 on 2023-06-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_picture_description_alter_picture_tagged_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='App/pictures'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='cover',
            field=models.ImageField(upload_to='App/social/coverPic/'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='profile_picture',
            field=models.ImageField(upload_to='App/social/profilePic/'),
        ),
    ]
