# Generated by Django 4.0 on 2023-06-14 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0008_alter_picture_image_alter_profiles_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='Profiles_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
