# Generated by Django 4.0 on 2023-06-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_profiles_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profile_picture',
            field=models.ImageField(upload_to='App/social/profilePic/'),
        ),
    ]
