# Generated by Django 4.0 on 2023-07-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_chatt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
