# Generated by Django 4.0 on 2023-05-25 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='option',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Myapp.option'),
            preserve_default=False,
        ),
    ]
